name: Push to main testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        with:
          python-version: 3.10.4
        uses: actions/setup-python@v4
      - name: Install dependencies
        uses: actions/setup-python@v4
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with Pytest
        run: pytest test_hello.py